#+TITLE:     A simple patched DWM config
#+AUTHOR:    quasinormalguy

*** List of applied patches:

dwm-alpha-20201019-61bb8b2.diff

dwm-alternativetags-6.2.diff

dwm-attachdirection-6.2.diff

dwm-autostart-20210120-cb3f58a.diff

dwm-bar-height-6.2.diff

dwm-cool-autostart-6.2.diff

dwm-cyclelayouts-20180524-6.2.diff

dwm-fullgaps-toggle-20200830.diff

dwm-gridmode-20170909-ceac8c9.diff

dwm-pertag-perseltag-6.2.diff

dwm-resizecorners-6.2.diff

dwm-rotatestack-20161021-ab9571b.diff

dwm-switchtotag-6.2.diff

dwm-tatami-6.2.diff

dwm-togglefloatingcenter-20210806-138b405f.diff

dwm-winicon-6.2-v1.3.diff


*** How-to's

- For winicon patch to work Imlib2 library is needed. Install by:
  
  ~sudo apt install libimlib2-dev~
  
  /-or-/
  
  ~sudo pacman -S imlib~.

- In config.def.h, default terminal is set to [[https://sw.kovidgoyal.net/kitty/][kitty]] (may want change it to yours).

- The Mod key is set as Super key.

- Add =dwm.desktop= to ~/usr/share/xsessions/~ for display manager to detect.

- The =autostart.sh= script should be modified to add commands that need to be run at startup.

- Another =autostart_blocking.sh= could also be created if there are some programs that you want make sure are killed before dwm starts.

- Another way to run autostart commands is in =config.def.h=. Here add only the commands which you want to get killed when you log out such as compositor.

- Do all other required edits and run ~sudo make clean install~.

\\
It is advisable to read the details of the applied [[https://dwm.suckless.org/patches/][patches on suckless website]].

\\
Configurations for 3rd party bars/panels (like [[https://github.com/mihirlad55/polybar-dwm-module][polybar]]) can be built on top of this. For this reason the systray patch was not applied. I you prefer to use only dwm's bar, it will be a good idea to apply the [[https://dwm.suckless.org/patches/systray/][systray patch]] for system tray programs, and write a script for status monitor or use of one of the status monitors [[https://dwm.suckless.org/status_monitor/][listed here]].

\\
*Cheers!*
