#+TITLE:     A simple patched DWM config
#+AUTHOR:    quasinormalguy

*** List of applied patches:

dwm-alpha-20201019-61bb8b2.diff

dwm-alternativetags-6.2.diff

dwm-attachdirection-6.2.diff

dwm-autostart-20210120-cb3f58a.diff

dwm-bar-height-6.2.diff

dwm-cool-autostart-6.2.diff

dwm-cyclelayouts-20180524-6.2.diff

dwm-fullgaps-toggle-20200830.diff

dwm-gridmode-20170909-ceac8c9.diff

dwm-pertag-perseltag-6.2.diff

dwm-resizecorners-6.2.diff

dwm-rotatestack-20161021-ab9571b.diff

dwm-switchtotag-6.2.diff

dwm-tatami-6.2.diff

dwm-togglefloatingcenter-20210806-138b405f.diff

dwm-winicon-6.2-v1.3.diff

\\
*** How-to's

- For winicon patch to work Imlib2 library is needed. Install by:
  
  ~sudo apt install libimlib2-dev~
  
  /-or-/
  
  ~sudo pacman -S imlib~.

- In config.def.h, default terminal is set to [[https://sw.kovidgoyal.net/kitty/][kitty]] (may want change it to yours).

- The Mod key is set as Super key.

- Add =dwm.desktop= to ~/usr/share/xsessions/~ for display manager to detect.

- Do all other required edits and run src_sh{sudo make clean install}.

\\
It is advisable to read the details of the applied [[https://dwm.suckless.org/patches/][patches on suckless website]].

\\
Configurations for 3rd party bars (like [[https://github.com/mihirlad55/polybar-dwm-module][polybar]]) can be built on top of this.

\\
*Cheers!*
